# Default database configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# Development environment
development:
  <<: *default
  database: budget_app_development
  username: test3
  password: test3
  port: 5432
  host: localhost

# Test environment
test:
  <<: *default
  database: budget_app_test
  username: test3
  password: test3
  port: 5432
  host: localhost

# Production environment
production:
  production:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>